SCREEN_TITTLE: "1 foto / 1  euro"
SCREEN_SUBTITLE: "INSERT COIN"
FRAME_TITTLE: "<< Fotomatón de Nila >>"
PICTURE_BORDER_SIZE: 20
COUNTDOWN_TIME: 8
FRAME_THICKNESS: 40

# UNCOMMENT SETTINGS

#PICTURE_BORDER_COLOR 
#BLINK_ENABLED 
#BLINK_SPEED 
#COIN_PIN
#LED_PIN
#SCREEN_WIDTH
#SCREEN_HEIGHT 
#FULLSCREEN 
#FRAME_ENABLED 
#FRAME_THICKNESS 
#FRAME_COLOR 
#FRAME_INNER_COLOR 
#FRAME_INNER_THICKNESS  
#FRAME_ROUNDED 
#FRAME_CORNER_RADIUS
